<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { Lock, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useUserStore } from '../../stores/user'
const store=useUserStore(),router=useRouter(),route=useRoute(),loading=ref(false)
const form=reactive({account:'',password:'',remember:true})
const submit=async()=>{if(!form.account.trim()||!form.password)return ElMessage.warning('请输入账号和密码');loading.value=true;try{await store.login(form.account.trim(),form.password);ElMessage.success('欢迎回来');router.push(String(route.query.redirect||'/'))}catch{/* 请求层统一展示后端错误。 */}finally{loading.value=false}}
</script>
<template><div class="auth-page"><div class="auth-scene"><router-link class="logo light" to="/"><span class="logo-symbol">✈</span><span>PlanGo</span></router-link><div><span class="eyebrow">WELCOME BACK</span><h1>世界很大，<br>继续你的下一段旅程。</h1><p>AI 会记住你的旅行偏好，帮你把灵感变成可出发的计划。</p></div><div class="scene-quote">“旅行的意义，是在陌生的地方重新认识自己。”</div></div><div class="auth-panel"><div class="auth-card"><h2>登录账号</h2><p>使用用户名或邮箱登录</p><el-form label-position="top" size="large" @submit.prevent="submit"><el-form-item label="用户名 / 邮箱"><el-input v-model="form.account" :prefix-icon="User" placeholder="请输入账号" autocomplete="username"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" :prefix-icon="Lock" type="password" show-password placeholder="请输入密码" autocomplete="current-password" @keyup.enter="submit"/></el-form-item><div class="auth-options"><el-checkbox v-model="form.remember">记住我</el-checkbox><a>忘记密码？</a></div><el-button class="gradient-button auth-submit" type="primary" :loading="loading" @click="submit">登录</el-button></el-form><p class="auth-switch">还没有账号？<router-link to="/register">免费注册</router-link></p></div></div></div></template>
<style scoped>.auth-page{min-height:100vh;display:grid;grid-template-columns:1.08fr .92fr;background:#fff}.auth-scene{padding:45px 9%;display:flex;flex-direction:column;justify-content:space-between;color:#fff;background:linear-gradient(135deg,rgba(21,55,98,.92),rgba(14,133,143,.72)),url('/assets/hero-chongqing-v2.png') center/cover}.light{color:#fff}.auth-scene h1{font-size:48px;line-height:1.25;margin:14px 0}.auth-scene p{color:#dbe8ef;font-size:16px;line-height:1.8;max-width:500px}.scene-quote{font-size:13px;color:#d8e7ed;border-left:3px solid #6ee7d8;padding-left:14px}.auth-panel{display:grid;place-items:center;padding:50px}.auth-card{width:430px}.auth-card h2{font-size:30px;margin:0 0 8px}.auth-card>p{color:#8992a0;margin-bottom:30px}.auth-options{display:flex;justify-content:space-between;margin:-4px 0 22px;font-size:13px}.auth-options a,.auth-switch a{color:var(--blue)}.auth-submit{width:100%;height:48px}.demo-tip{background:#f0f7ff;color:#52769e;padding:10px;text-align:center;border-radius:10px;font-size:12px;margin-top:18px}.auth-switch{text-align:center!important;font-size:13px}</style>
