<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ChatDotRound, Collection, EditPen, Search, Star } from '@element-plus/icons-vue'
import { baseApi, noteApi } from '../../api'
import type { Note } from '../../types'
const router=useRouter(),loading=ref(false),items=ref<Note[]>([]),tagList=ref<any[]>([]),total=ref(0),params=reactive({pageNum:1,pageSize:9,keyword:'',tagId:0,sort:'latest'})
const load=async()=>{loading.value=true;try{const data=await noteApi.list(params);items.value=data.list;total.value=data.total}finally{loading.value=false}}
const chooseTag=(id:number)=>{params.tagId=id;params.pageNum=1;load()}
onMounted(async()=>{tagList.value=await baseApi.tags();load()})
</script>
<template><div class="notes-page"><section class="notes-hero"><div class="container"><span class="eyebrow">TRAVEL COMMUNITY</span><h1>在真实故事里，遇见下一站</h1><p>旅行者分享的路线、味道与那些计划之外的惊喜。</p><div class="note-search"><el-input v-model="params.keyword" :prefix-icon="Search" size="large" placeholder="搜索目的地、游记标题" @keyup.enter="load"/><el-button class="gradient-button" type="primary" size="large" @click="load">搜索灵感</el-button></div></div></section><div class="container note-content"><div class="note-toolbar"><div class="tag-filters"><button :class="{active:!params.tagId}" @click="chooseTag(0)">全部</button><button v-for="tag in tagList" :key="tag.id" :class="{active:params.tagId===tag.id}" @click="chooseTag(tag.id)">{{tag.name}}</button></div><div><el-radio-group v-model="params.sort" @change="load"><el-radio-button label="latest">最新</el-radio-button><el-radio-button label="hot">热门</el-radio-button></el-radio-group><el-button type="primary" :icon="EditPen" @click="router.push('/notes/create')">发布游记</el-button></div></div><div v-loading="loading" class="notes-grid" v-if="items.length"><article v-for="note in items" :key="note.id" class="note-card card" @click="router.push(`/notes/${note.id}`)"><div class="cover"><img :src="note.coverUrl"><span>{{note.destination}}</span></div><div class="note-body"><div class="note-date">{{note.createTime}}</div><h2>{{note.title}}</h2><p>{{note.summary}}</p><div class="note-tags"><el-tag v-for="tag in note.tags" :key="tag" size="small" effect="light">{{tag}}</el-tag></div><div class="note-meta"><el-avatar :size="30" :src="note.authorAvatarUrl"/><b>{{note.authorNickname}}</b><span><el-icon><Star/></el-icon>{{note.likeCount}}</span><span><el-icon><Collection/></el-icon>{{note.favoriteCount}}</span><span><el-icon><ChatDotRound/></el-icon>{{note.commentCount}}</span></div></div></article></div><div v-else class="empty-wrap card"><el-empty description="暂无符合条件的游记"/></div><div class="pagination"><el-pagination v-model:current-page="params.pageNum" :page-size="params.pageSize" :total="total" layout="prev, pager, next" @current-change="load"/></div></div></div></template>
<style scoped>.notes-hero{text-align:center;padding:70px 0 95px;background:linear-gradient(120deg,#edf8ff,#e7f8f1)}.notes-hero h1{font-size:42px;margin:10px}.notes-hero p{color:#6e7b8d}.note-search{display:flex;width:620px;margin:28px auto 0;padding:8px;background:#fff;border-radius:16px;box-shadow:0 14px 38px #3568891c}.note-search :deep(.el-input__wrapper){box-shadow:none}.note-content{margin-top:-35px}.note-toolbar{display:flex;align-items:center;justify-content:space-between;background:#fff;border-radius:18px;padding:14px 16px;box-shadow:0 10px 30px #3d5d7c12;margin-bottom:24px}.tag-filters{display:flex;gap:7px}.tag-filters button{border:0;background:transparent;padding:9px 13px;border-radius:99px;color:#667487;cursor:pointer}.tag-filters button.active{color:#fff;background:var(--gradient)}.note-toolbar>div:last-child{display:flex;gap:10px}.notes-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;min-height:300px}.note-card{overflow:hidden;cursor:pointer;transition:.25s}.note-card:hover{transform:translateY(-5px);box-shadow:0 18px 45px #31506d20}.cover{height:220px;position:relative;overflow:hidden}.cover img{width:100%;height:100%;object-fit:cover;transition:.4s}.note-card:hover img{transform:scale(1.04)}.cover span{position:absolute;left:15px;top:15px;background:#17293ca8;color:#fff;padding:6px 10px;border-radius:99px;font-size:11px}.note-body{padding:20px}.note-date{font-size:10px;color:#9aa2ae}.note-body h2{font-size:18px;line-height:1.4;margin:8px 0}.note-body>p{color:#778293;font-size:13px;line-height:1.65;height:42px}.note-tags .el-tag{border:0;margin-right:6px}.note-meta{display:flex;align-items:center;gap:7px;padding-top:15px;margin-top:16px;border-top:1px solid #edf0f4;font-size:11px;color:#7f8997}.note-meta b{margin-right:auto;color:#475366}.note-meta span{display:flex;align-items:center;gap:3px}.pagination{display:flex;justify-content:center;margin-top:30px}</style>
