<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { DocumentChecked, UploadFilled } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { baseApi, noteApi } from '../../api'
const route=useRoute(),router=useRouter(),loading=ref(false),tagList=ref<any[]>([]),isEdit=Boolean(route.params.id)
const form=reactive({title:'',coverUrl:'/assets/chongqing.jpg',destination:'重庆',summary:'',content:'# 写下你的旅行故事\n\n从这里开始记录...',tagIds:[] as number[],status:1})
onMounted(async()=>{tagList.value=await baseApi.tags();if(isEdit){const data=await noteApi.detail(Number(route.params.id));Object.assign(form,{...data,tagIds:data.tagIds})}})
const chooseCover=(file:any)=>{form.coverUrl=URL.createObjectURL(file.raw)}
const submit=async(status:number)=>{if(!form.title||!form.destination||!form.summary||!form.content)return ElMessage.warning('请完整填写标题、目的地、摘要和正文');loading.value=true;try{const selected=tagList.value.filter(t=>form.tagIds.includes(t.id)).map(t=>t.name);const data=await noteApi.save({...form,status,tags:selected},isEdit?Number(route.params.id):undefined);ElMessage.success(status===0?'草稿已保存':'游记已发布');router.push(`/notes/${data.id}`)}finally{loading.value=false}}
</script>
<template><div class="page editor-page"><div class="container editor-container"><div class="editor-head"><div><span class="eyebrow">TRAVEL JOURNAL</span><h1>{{isEdit?'编辑游记':'发布一篇新游记'}}</h1><p>把风景之外的感受，也认真记录下来。</p></div><div><el-button @click="submit(0)">保存草稿</el-button><el-button class="gradient-button" type="primary" :loading="loading" @click="submit(1)"><el-icon><DocumentChecked/></el-icon>{{isEdit?'保存修改':'发布游记'}}</el-button></div></div><div class="editor-layout"><section class="editor-main card"><el-form label-position="top"><el-form-item label="游记标题"><el-input v-model="form.title" size="large" maxlength="60" show-word-limit placeholder="给这段旅程起一个吸引人的标题"/></el-form-item><div class="form-row"><el-form-item label="目的地"><el-input v-model="form.destination" placeholder="例如：重庆"/></el-form-item><el-form-item label="标签"><el-select v-model="form.tagIds" multiple placeholder="选择标签" style="width:100%"><el-option v-for="tag in tagList" :key="tag.id" :label="tag.name" :value="tag.id"/></el-select></el-form-item></div><el-form-item label="摘要"><el-input v-model="form.summary" type="textarea" :rows="3" maxlength="120" show-word-limit placeholder="用一两句话介绍这篇游记"/></el-form-item><el-form-item label="正文"><v-md-editor v-model="form.content" height="520px"/></el-form-item></el-form></section><aside class="cover-panel card"><h3>游记封面</h3><div class="cover-preview"><img :src="form.coverUrl"><div><el-icon><UploadFilled/></el-icon><span>建议尺寸 16:9</span></div></div><el-upload :auto-upload="false" :show-file-list="false" accept="image/*" @change="chooseCover"><el-button style="width:100%">选择本地图片</el-button></el-upload><p>当前为前端演示，图片仅做本地预览。后续接入文件上传接口。</p><h3>发布提示</h3><ul><li>真实、友善地分享旅行体验</li><li>避免泄露个人隐私信息</li><li>标题与封面应和正文相关</li></ul></aside></div></div></div></template>
<style scoped>.editor-container{max-width:1320px}.editor-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:25px}.editor-head h1{font-size:34px;margin:8px 0}.editor-head p{color:#7a8594}.editor-layout{display:grid;grid-template-columns:1fr 290px;gap:20px;align-items:start}.editor-main{padding:28px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:18px}.cover-panel{padding:22px;position:sticky;top:92px}.cover-panel h3{margin:0 0 14px}.cover-preview{height:155px;border-radius:14px;overflow:hidden;position:relative;margin-bottom:12px;background:#edf2f7}.cover-preview img{width:100%;height:100%;object-fit:cover}.cover-preview>div{position:absolute;inset:0;background:#17283b75;color:#fff;display:flex;align-items:center;justify-content:center;gap:7px;opacity:0;transition:.2s}.cover-preview:hover>div{opacity:1}.cover-panel>p,.cover-panel li{color:#7e8897;font-size:12px;line-height:1.7}.cover-panel h3:nth-of-type(2){margin-top:28px}.cover-panel ul{padding-left:18px}</style>
