<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ChatDotRound, Collection, Delete, Edit, Star, View } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { noteApi } from '../../api'
import { useUserStore } from '../../stores/user'
import type { Comment, Note } from '../../types'
const route=useRoute(),router=useRouter(),store=useUserStore(),note=ref<Note|null>(null),comments=ref<Comment[]>([]),loading=ref(true),content=ref(''),sending=ref(false)
const id=computed(()=>Number(route.params.id)),isAuthor=computed(()=>store.user?.id===note.value?.authorId)
const scrollToComments=()=>document.querySelector('.comments')?.scrollIntoView({behavior:'smooth'})
const articleHtml=computed(()=>{const raw=note.value?.content||'';const safe=raw.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return safe.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^> (.*)$/gm,'<blockquote>$1</blockquote>').replace(/\n\n/g,'</p><p>')})
const load=async()=>{loading.value=true;try{note.value=await noteApi.detail(id.value);comments.value=await noteApi.getComments(id.value)}finally{loading.value=false}}
const ensureLogin=()=>{if(!store.isLogin){router.push({path:'/login',query:{redirect:route.fullPath}});return false}return true}
const like=async()=>{if(!ensureLogin()||!note.value)return;await noteApi.toggleLike(id.value,!note.value.liked);note.value.liked=!note.value.liked;note.value.likeCount+=note.value.liked?1:-1}
const favorite=async()=>{if(!ensureLogin()||!note.value)return;await noteApi.toggleFavorite(id.value,!note.value.favorited);note.value.favorited=!note.value.favorited;note.value.favoriteCount+=note.value.favorited?1:-1}
const add=async()=>{if(!ensureLogin()||!content.value.trim())return;sending.value=true;try{comments.value.push(await noteApi.addComment(id.value,content.value));content.value='';ElMessage.success('评论已发布')}finally{sending.value=false}}
const remove=async()=>{await ElMessageBox.confirm('确定删除这篇游记吗？','删除游记',{type:'warning'});await noteApi.remove(id.value);router.push('/notes')}
onMounted(load)
</script>
<template><div class="note-detail-page" v-loading="loading" v-if="note"><section class="article-cover"><img :src="note.coverUrl"><div class="cover-mask"></div><div class="container cover-content"><el-tag effect="dark">{{note.destination}}</el-tag><h1>{{note.title}}</h1><p>{{note.summary}}</p><div class="cover-author"><el-avatar :size="40" :src="note.authorAvatarUrl"/><span><b>{{note.authorNickname}}</b><small>{{note.createTime}} · 2,680 次阅读</small></span><div v-if="isAuthor"><el-button :icon="Edit" @click="router.push(`/notes/edit/${note.id}`)">编辑</el-button><el-button type="danger" plain :icon="Delete" @click="remove">删除</el-button></div></div></div></section><main class="article-layout container"><article class="article card"><div class="article-tags"><el-tag v-for="tag in note.tags" :key="tag" effect="light"># {{tag}}</el-tag></div><div class="markdown-body" v-html="`<p>${articleHtml}</p>`"></div></article><aside><div class="interaction-card card"><button :class="{active:note.liked}" @click="like"><el-icon><Star/></el-icon><b>{{note.likeCount}}</b><span>{{note.liked?'已点赞':'点赞'}}</span></button><button :class="{active:note.favorited}" @click="favorite"><el-icon><Collection/></el-icon><b>{{note.favoriteCount}}</b><span>{{note.favorited?'已收藏':'收藏'}}</span></button><button @click="scrollToComments"><el-icon><ChatDotRound/></el-icon><b>{{note.commentCount}}</b><span>评论</span></button></div><div class="author-card card"><el-avatar :size="58" :src="note.authorAvatarUrl"/><h3>{{note.authorNickname}}</h3><p>热爱城市漫游，也认真记录每一次出发。</p><el-button round>关注旅行者</el-button></div></aside></main><section class="comments container"><div class="comment-panel card"><h2>评论 <small>{{comments.length}}</small></h2><div class="comment-compose"><el-avatar :size="38" :src="store.user?.avatarUrl"/><el-input v-model="content" type="textarea" :rows="3" placeholder="分享你的想法，或向作者提问..."/><el-button class="gradient-button" type="primary" :loading="sending" @click="add">发表评论</el-button></div><div class="comment-list"><article v-for="item in comments" :key="item.id"><el-avatar :size="38" :src="item.avatarUrl"/><div><b>{{item.nickname}}</b><time>{{item.createTime}}</time><p>{{item.content}}</p></div></article><el-empty v-if="!comments.length" description="暂无评论，来坐第一排吧" :image-size="80"/></div></div></section></div></template>
<style scoped>.article-cover{height:500px;position:relative}.article-cover>img{width:100%;height:100%;object-fit:cover}.cover-mask{position:absolute;inset:0;background:linear-gradient(transparent 10%,rgba(7,16,26,.88))}.cover-content{position:absolute;left:0;right:0;bottom:48px;color:#fff}.cover-content h1{font-size:42px;max-width:900px;margin:14px 0 10px}.cover-content>p{color:#dbe3ea}.cover-author{display:flex;align-items:center;gap:11px;margin-top:22px}.cover-author span{display:flex;flex-direction:column}.cover-author small{color:#cbd6df;margin-top:4px}.cover-author>div{margin-left:auto}.article-layout{display:grid;grid-template-columns:1fr 280px;gap:24px;margin-top:30px;align-items:start}.article{padding:42px 55px}.article-tags{display:flex;gap:7px;margin-bottom:28px}.article-tags .el-tag{border:0}.markdown-body{font-size:16px;line-height:2;color:#364154}.markdown-body :deep(h1){font-size:28px;margin:28px 0 10px}.markdown-body :deep(h2){font-size:22px;margin:26px 0 8px}.markdown-body :deep(blockquote){border-left:4px solid #5ba7e8;background:#f2f7fb;margin:24px 0;padding:14px 18px;color:#60758a}.interaction-card{display:grid;grid-template-columns:repeat(3,1fr);padding:12px}.interaction-card button{border:0;background:transparent;padding:10px 4px;display:flex;flex-direction:column;align-items:center;gap:3px;color:#7d8797;cursor:pointer}.interaction-card button:not(:last-child){border-right:1px solid #edf0f4}.interaction-card button .el-icon{font-size:20px}.interaction-card button b{color:#334054}.interaction-card button span{font-size:10px}.interaction-card button.active,.interaction-card button.active b{color:#2f80ed}.author-card{text-align:center;padding:25px;margin-top:16px}.author-card h3{margin:10px 0 6px}.author-card p{color:#7f8997;font-size:12px;line-height:1.6}.comments{max-width:950px;margin-top:28px}.comment-panel{padding:28px}.comment-panel h2{margin-top:0}.comment-panel h2 small{color:#9aa2ad}.comment-compose{display:grid;grid-template-columns:40px 1fr auto;gap:12px;align-items:start;background:#f7f9fc;padding:16px;border-radius:15px}.comment-list article{display:flex;gap:12px;padding:20px 4px;border-bottom:1px solid #edf0f4}.comment-list article>div{flex:1}.comment-list time{font-size:11px;color:#9aa2ae;margin-left:10px}.comment-list p{color:#5f6b7b;margin:8px 0}</style>
