<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Calendar, EditPen, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { userApi } from '../../api'
import { useUserStore } from '../../stores/user'
const store=useUserStore(),router=useRouter(),loading=ref(true),saving=ref(false),form=reactive({nickname:'',avatarUrl:'',username:'',email:'',createTime:''})
onMounted(async()=>{const data=await userApi.me();Object.assign(form,data);loading.value=false})
const save=async()=>{saving.value=true;try{await userApi.update({nickname:form.nickname,avatarUrl:form.avatarUrl});const data=await userApi.me();Object.assign(form,data);store.updateUser(data);ElMessage.success('个人资料已更新')}catch{/* 请求层统一展示后端错误。 */}finally{saving.value=false}}
</script>
<template><div class="page profile-page"><div class="container profile-container" v-loading="loading"><section class="profile-hero card"><div class="profile-bg"></div><div class="profile-main"><el-avatar :size="92" :src="form.avatarUrl"><User/></el-avatar><div><h1>{{form.nickname}}</h1><p>@{{form.username}} · 从 {{form.createTime?.slice(0,10)}} 开始探索</p></div><el-tag type="success" size="large">普通用户</el-tag></div></section><div class="profile-grid"><section class="profile-form card"><div class="section-title"><div><h2>个人资料</h2><p>修改你的公开昵称和头像。</p></div></div><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="form.username" disabled/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email" disabled/></el-form-item><el-form-item label="昵称"><el-input v-model="form.nickname"/></el-form-item><el-form-item label="头像地址"><el-input v-model="form.avatarUrl"/></el-form-item><el-button class="gradient-button" type="primary" :loading="saving" @click="save">保存资料</el-button></el-form></section><aside><article class="shortcut card" @click="router.push('/trips')"><span><el-icon><Calendar/></el-icon></span><div><h3>我的行程</h3><p>查看和管理已保存的旅行计划</p></div>→</article><article class="shortcut card" @click="router.push('/notes/create')"><span class="green"><el-icon><EditPen/></el-icon></span><div><h3>发布游记</h3><p>记录旅途故事，分享给更多人</p></div>→</article></aside></div></div></div></template>
<style scoped>.profile-container{max-width:1000px}.profile-hero{overflow:hidden}.profile-bg{height:150px;background:linear-gradient(120deg,#2f80edba,#00b89491),url('/assets/hero-chongqing-v2.png') center/cover}.profile-main{display:flex;align-items:center;gap:18px;padding:0 35px 28px;margin-top:-42px}.profile-main .el-avatar{border:5px solid #fff}.profile-main h1{margin:50px 0 5px}.profile-main p{color:#7e8897;margin:0}.profile-main .el-tag{margin-left:auto;margin-top:45px}.profile-grid{display:grid;grid-template-columns:1fr 340px;gap:20px;margin-top:20px}.profile-form{padding:28px}.profile-grid aside{display:grid;gap:14px;align-content:start}.shortcut{padding:20px;display:flex;align-items:center;gap:13px;cursor:pointer}.shortcut>span{width:45px;height:45px;border-radius:14px;background:#e8f3ff;color:#2f80ed;display:grid;place-items:center;font-size:20px}.shortcut>span.green{background:#e5f8f2;color:#00a57c}.shortcut h3,.shortcut p{margin:0}.shortcut p{color:#8992a0;font-size:11px;margin-top:4px}.shortcut>div{flex:1}</style>
