<script setup lang="ts">
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Calendar, EditPen, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { userApi, fileApi } from '../../api'
import { useUserStore } from '../../stores/user'
const store=useUserStore(),router=useRouter(),loading=ref(true),saving=ref(false),uploading=ref(false),fileInputRef=ref<HTMLInputElement|null>(null),form=reactive({nickname:'',avatarUrl:'',username:'',email:'',createTime:''})
// 修改邮箱相关状态
const emailDialogVisible=ref(false),emailChanging=ref(false),emailCodeSending=ref(false),emailCodeSeconds=ref(0);let emailCodeTimer:number|null=null
const emailForm=reactive({newEmail:'',emailCode:''})
onMounted(async()=>{const data=await userApi.me();Object.assign(form,data);loading.value=false})
onUnmounted(()=>{if(emailCodeTimer!==null){clearInterval(emailCodeTimer);emailCodeTimer=null}})
const save=async()=>{saving.value=true;try{await userApi.update({nickname:form.nickname,avatarUrl:form.avatarUrl});const data=await userApi.me();Object.assign(form,data);store.updateUser(data);ElMessage.success('个人资料已更新')}catch{/* 请求层统一展示后端错误。 */}finally{saving.value=false}}
const triggerUpload=()=>fileInputRef.value?.click()
const onFileSelected=async()=>{const input=fileInputRef.value;if(!input?.files?.length)return;const file=input.files[0];const allowed=['image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){ElMessage.warning('仅支持 JPG、PNG、WebP 格式');input.value='';return}if(file.size>5*1024*1024){ElMessage.warning('文件大小不能超过 5MB');input.value='';return}uploading.value=true;try{const res=await fileApi.upload(file,'avatar');form.avatarUrl=res.url;ElMessage.success('头像上传成功，请点击保存资料生效')}catch{/* 请求层统一展示后端错误。 */}finally{uploading.value=false;input.value=''}}
// 修改邮箱
const openEmailDialog=()=>{emailForm.newEmail='';emailForm.emailCode='';if(emailCodeTimer!==null){clearInterval(emailCodeTimer);emailCodeTimer=null}emailCodeSeconds.value=0;emailDialogVisible.value=true}
const closeEmailDialog=()=>{if(emailCodeTimer!==null){clearInterval(emailCodeTimer);emailCodeTimer=null}emailCodeSeconds.value=0;emailForm.newEmail='';emailForm.emailCode='';emailDialogVisible.value=false}
const sendEmailCode=async()=>{const re=/^\S+@\S+\.\S+$/;if(!emailForm.newEmail.trim())return ElMessage.warning('请输入新邮箱');if(!re.test(emailForm.newEmail.trim()))return ElMessage.warning('邮箱格式不正确');if(emailForm.newEmail.trim().toLowerCase()===form.email?.trim().toLowerCase())return ElMessage.warning('新邮箱不能与当前邮箱相同');emailCodeSending.value=true;try{await userApi.sendChangeEmailCode(emailForm.newEmail.trim());ElMessage.success('验证码已发送，请查收新邮箱');emailCodeSeconds.value=60;emailCodeTimer=window.setInterval(()=>{emailCodeSeconds.value--;if(!emailCodeSeconds.value&&emailCodeTimer!==null){clearInterval(emailCodeTimer);emailCodeTimer=null}},1000)}catch{/* 请求层统一展示后端错误。 */}finally{emailCodeSending.value=false}}
const confirmChangeEmail=async()=>{const re=/^\S+@\S+\.\S+$/;if(!emailForm.newEmail.trim()||!re.test(emailForm.newEmail.trim()))return ElMessage.warning('请输入正确的新邮箱');if(!emailForm.emailCode.trim()||emailForm.emailCode.trim().length!==6)return ElMessage.warning('请输入 6 位验证码');emailChanging.value=true;try{await userApi.updateEmail({newEmail:emailForm.newEmail.trim(),emailCode:emailForm.emailCode.trim()});ElMessage.success('邮箱修改成功');closeEmailDialog();const data=await userApi.me();Object.assign(form,data);store.updateUser(data)}catch{/* 请求层统一展示后端错误。 */}finally{emailChanging.value=false}}
</script>
<template><div class="page profile-page"><div class="container profile-container" v-loading="loading"><section class="profile-hero card"><div class="profile-bg"></div><div class="profile-main"><el-avatar :size="92" :src="form.avatarUrl"><User/></el-avatar><div><h1>{{form.nickname}}</h1><p>@{{form.username}} · 从 {{form.createTime?.slice(0,10)}} 开始探索</p></div><el-tag type="success" size="large">普通用户</el-tag></div></section><div class="profile-grid"><section class="profile-form card"><div class="section-title"><div><h2>个人资料</h2><p>修改你的公开昵称和头像。</p></div></div><el-form label-position="top"><el-form-item label="用户名"><el-input v-model="form.username" disabled/></el-form-item><el-form-item label="邮箱"><div class="email-row"><span class="email-text">{{form.email||'未设置'}}</span><el-button size="small" type="primary" plain @click="openEmailDialog">修改邮箱</el-button></div></el-form-item><el-form-item label="昵称"><el-input v-model="form.nickname"/></el-form-item><el-form-item label="头像"><el-button :loading="uploading" type="primary" plain @click="triggerUpload">上传头像</el-button><input ref="fileInputRef" type="file" accept="image/jpeg,image/png,image/webp" style="display:none" @change="onFileSelected"/></el-form-item><el-button class="gradient-button" type="primary" :loading="saving" @click="save">保存资料</el-button></el-form></section><aside><article class="shortcut card" @click="router.push('/trips')"><span><el-icon><Calendar/></el-icon></span><div><h3>我的行程</h3><p>查看和管理已保存的旅行计划</p></div>→</article><article class="shortcut card" @click="router.push('/notes/create')"><span class="green"><el-icon><EditPen/></el-icon></span><div><h3>发布游记</h3><p>记录旅途故事，分享给更多人</p></div>→</article></aside></div></div></div><el-dialog v-model="emailDialogVisible" title="修改邮箱" width="420px" :close-on-click-modal="false" @close="closeEmailDialog"><el-form label-position="top"><el-form-item label="新邮箱"><el-input v-model="emailForm.newEmail" placeholder="请输入新邮箱地址" maxlength="100"/></el-form-item><el-form-item label="验证码"><div class="code-row"><el-input v-model="emailForm.emailCode" placeholder="6 位验证码" maxlength="6"/><el-button :loading="emailCodeSending" :disabled="emailCodeSeconds>0" @click="sendEmailCode">{{emailCodeSeconds?`${emailCodeSeconds}s 后重试`:'发送验证码'}}</el-button></div></el-form-item></el-form><template #footer><el-button @click="closeEmailDialog">取消</el-button><el-button type="primary" :loading="emailChanging" @click="confirmChangeEmail">确认修改</el-button></template></el-dialog></template>
<style scoped>.profile-container{max-width:1000px}.profile-hero{overflow:hidden}.profile-bg{height:150px;background:linear-gradient(120deg,#2f80edba,#00b89491),url('/assets/hero-chongqing-v2.png') center/cover}.profile-main{display:flex;align-items:center;gap:18px;padding:0 35px 28px;margin-top:-42px}.profile-main .el-avatar{border:5px solid #fff}.profile-main h1{margin:50px 0 5px}.profile-main p{color:#7e8897;margin:0}.profile-main .el-tag{margin-left:auto;margin-top:45px}.profile-grid{display:grid;grid-template-columns:1fr 340px;gap:20px;margin-top:20px}.profile-form{padding:28px}.profile-grid aside{display:grid;gap:14px;align-content:start}.shortcut{padding:20px;display:flex;align-items:center;gap:13px;cursor:pointer}.shortcut>span{width:45px;height:45px;border-radius:14px;background:#e8f3ff;color:#2f80ed;display:grid;place-items:center;font-size:20px}.shortcut>span.green{background:#e5f8f2;color:#00a57c}.shortcut h3,.shortcut p{margin:0}.shortcut p{color:#8992a0;font-size:11px;margin-top:4px}.shortcut>div{flex:1}.email-row{display:flex;align-items:center;gap:12px}.email-text{color:#303133;font-size:14px}.code-row{display:flex;width:100%;gap:10px}.code-row .el-button{white-space:nowrap}</style>
