<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { authApi } from '../../api'
const router=useRouter(),loading=ref(false),seconds=ref(0)
const form=reactive({username:'',email:'',password:'',confirmPassword:'',emailCode:'',agree:false})
const sendCode=async()=>{if(!/^\S+@\S+\.\S+$/.test(form.email))return ElMessage.warning('请输入正确的邮箱');await authApi.sendCode(form.email);ElMessage.success('验证码已发送，演示环境任意填写');seconds.value=60;const timer=setInterval(()=>{seconds.value--;if(!seconds.value)clearInterval(timer)},1000)}
const submit=async()=>{if(!form.username||form.password.length<6||form.password!==form.confirmPassword||!form.emailCode)return ElMessage.warning('请完整、正确地填写表单');if(!form.agree)return ElMessage.warning('请同意用户协议');loading.value=true;try{await authApi.register(form);ElMessage.success('注册成功，请登录');router.push('/login')}finally{loading.value=false}}
</script>
<template><div class="register-page"><div class="register-card card"><router-link class="logo" to="/"><span class="logo-symbol">✈</span><span>AI智行伴旅</span></router-link><div class="register-head"><span class="eyebrow">CREATE ACCOUNT</span><h1>开始你的智能旅行</h1><p>注册后即可生成、保存和管理专属行程。</p></div><el-form label-position="top" size="large"><div class="form-row"><el-form-item label="用户名"><el-input v-model="form.username" placeholder="设置登录用户名"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email" placeholder="name@example.com"/></el-form-item></div><div class="form-row"><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password placeholder="至少 6 位"/></el-form-item><el-form-item label="确认密码"><el-input v-model="form.confirmPassword" type="password" show-password placeholder="再次输入密码"/></el-form-item></div><el-form-item label="邮箱验证码"><div class="code-row"><el-input v-model="form.emailCode" placeholder="演示环境任意填写"/><el-button :disabled="seconds>0" @click="sendCode">{{seconds?`${seconds}s 后重试`:'发送验证码'}}</el-button></div></el-form-item><el-checkbox v-model="form.agree">我已阅读并同意《用户协议》和《隐私政策》</el-checkbox><el-button class="gradient-button register-submit" type="primary" :loading="loading" @click="submit">创建账号</el-button></el-form><p>已有账号？<router-link to="/login">直接登录</router-link></p></div></div></template>
<style scoped>.register-page{min-height:100vh;padding:60px;display:grid;place-items:center;background:radial-gradient(circle at 12% 20%,#dff6f2 0,transparent 25%),radial-gradient(circle at 88% 75%,#e4f0ff 0,transparent 28%),#f6f9fc}.register-card{width:760px;padding:38px 48px}.register-head{text-align:center;margin:30px 0}.register-head h1{font-size:32px;margin:8px}.register-head p,.register-card>p{color:#87909e}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:18px}.code-row{display:flex;width:100%;gap:10px}.code-row .el-button{height:40px}.register-submit{width:100%;height:48px;margin-top:24px}.register-card>p{text-align:center;font-size:13px}.register-card>p a{color:var(--blue)}</style>
