<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Calendar, Coin, Delete, MagicStick, Search } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus/es/components/message/index'
import { ElMessageBox } from 'element-plus/es/components/message-box/index'
import { tripApi } from '../../api'
import type { Trip } from '../../types'
import { homeImage } from '../../utils/homeImages'
const router=useRouter(),loading=ref(false),items=ref<Trip[]>([]),total=ref(0),params=reactive({pageNum:1,pageSize:8,keyword:''})
const defaultTripCover=homeImage('chongqing.jpg')
const load=async()=>{loading.value=true;try{const data=await tripApi.list(params);items.value=data.list;total.value=data.total}finally{loading.value=false}}
const remove=async(item:Trip)=>{await ElMessageBox.confirm(`确定删除“${item.title}”吗？`,'删除行程',{type:'warning',confirmButtonText:'确定',cancelButtonText:'取消'});await tripApi.remove(item.id);ElMessage.success('已删除');load()}
const showDetailTodo=()=>ElMessage.info('行程详情页功能待完成，后续会完善')
onMounted(load)
</script>
<template><div class="page"><div class="container"><div class="page-hero"><span class="eyebrow">MY JOURNEYS</span><h1>我的行程</h1><p>每一次认真计划的出发，都值得被好好保存。</p></div><div class="toolbar card"><el-input v-model="params.keyword" :prefix-icon="Search" clearable placeholder="搜索行程标题或目的地" style="width:340px" @keyup.enter="load"/><el-button @click="load">搜索</el-button><div class="spacer"></div><el-button class="gradient-button" type="primary" @click="router.push('/ai-trip')"><el-icon><MagicStick/></el-icon>生成新行程</el-button></div><div v-loading="loading" class="trip-grid" v-if="items.length"><article v-for="item in items" :key="item.id" class="trip-card card"><div class="trip-cover"><img :src="item.coverUrl||defaultTripCover"><span>{{item.destination}}</span><button @click.stop="remove(item)"><el-icon><Delete/></el-icon></button></div><div class="trip-info" @click="showDetailTodo"><small>{{item.createTime}}</small><h3>{{item.title}}</h3><p>{{item.summary}}</p><div><span><el-icon><Calendar/></el-icon>{{item.days}} 天</span><span><el-icon><Coin/></el-icon>¥{{item.budget}}</span></div><el-tag v-for="tag in item.preferences" :key="tag" size="small" effect="light" @click.stop>{{tag}}</el-tag></div></article></div><div v-else class="empty-wrap card"><el-empty description="暂无行程，去生成你的第一个 AI 旅行计划吧"><el-button type="primary" @click="router.push('/ai-trip')">开始 AI 规划</el-button></el-empty></div><div class="pagination" v-if="total>params.pageSize"><el-pagination v-model:current-page="params.pageNum" :page-size="params.pageSize" :total="total" layout="prev, pager, next" @current-change="load"/></div></div></div></template>
<style scoped>.trip-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;min-height:300px}.trip-card{overflow:hidden}.trip-cover{height:190px;position:relative}.trip-cover img{width:100%;height:100%;object-fit:cover}.trip-cover>span{position:absolute;left:15px;top:14px;color:#fff;background:#182c3e9e;backdrop-filter:blur(5px);padding:6px 10px;border-radius:99px;font-size:12px}.trip-cover button{position:absolute;right:13px;top:13px;width:32px;height:32px;border:0;border-radius:50%;background:#ffffffda;color:#ef4444;cursor:pointer}.trip-info{padding:19px;cursor:pointer}.trip-info>small{color:#9aa2af}.trip-info h3{font-size:19px;margin:8px 0}.trip-info p{font-size:13px;color:#768192;line-height:1.65;height:42px}.trip-info>div{display:flex;gap:20px;color:#647184;font-size:13px;margin-bottom:13px}.trip-info>div span{display:flex;align-items:center;gap:5px}.trip-info .el-tag{border:0;margin-right:6px}.pagination{display:flex;justify-content:center;margin-top:28px}</style>
